Repository openshift/baremetal-runtimecfg, pull requests merged in 2019-07, with the labels that each got.

#4 Add OWNERS file
  OWNERS
Labels: size/XS

#5 Allow users to pass a single dir path to render
  cmd/runtimecfg.go
  go.mod
  go.sum
  pkg/render/render.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/modules.txt
Labels: approved, size/XXL

#9 Add EtcdShortHostname to Node
  pkg/config/node.go
  pkg/utils/utils.go
Labels: approved, size/S

#12 runtimecfg: Add DNS upstream servers for Corefile
  pkg/config/node.go
  test/data/Corefile.tmpl
Labels: approved, lgtm, size/M

#10 runtimecfg: Add EtcdShortHostname to test data
  test/data/config.hcl.tmpl
Labels: approved, size/XS
