Repository openshift/baremetal-runtimecfg, pull requests merged in 2019-11, with the labels that each got.

#30 Add test target for CI
  Makefile
Labels: lgtm, size/XS

#32 OWNERS: Add the rest of the team
  OWNERS
Labels: approved, size/XS

#29 Haproxy add support for IPv6 frontend
  pkg/config/node.go
  pkg/monitor/monitor.go
  test/data/haproxy.cfg.tmpl
Labels: approved, lgtm, size/S
