Repository openshift/baremetal-runtimecfg, pull requests merged in 2019-10, with the labels that each got.

#26 Check that go fmt has no changes
  Makefile
Labels: approved, lgtm, size/XS

#19 Add stabilization mechanism to monitor logic
  cmd/monitor/monitor.go
  pkg/monitor/monitor.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/M

#23 Tweak VRID calculation to avoid 0
  pkg/config/node.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/S

#25 Add EtcdBackends cluster member
  pkg/config/node.go
Labels: approved, lgtm, size/S

#28 Verify that Iptable rule being deleted
  pkg/monitor/monitor.go
Labels: approved, lgtm, size/XS

#27 Monitor - add IPv6 support
  Dockerfile
  pkg/monitor/iptables.go
  scripts/ip6tables
Labels: approved, lgtm, size/S
