Repository openshift/baremetal-runtimecfg, pull requests merged in 2020-10, with the labels that each got.

#102 Bug 1884420: bootstrap: API shows up, start it again
  pkg/monitor/dynkeepalived.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#95 Change local Dockerfile to use CentOS 8
  Dockerfile
Labels: approved, lgtm

#104 Updating baremetal-runtimecfg builder & base images to be consistent with ART
  Dockerfile.openshift
Labels: approved, lgtm

#106 Add bz component information
  OWNERS
Labels: approved, lgtm

#103 Bug 1885867 : Flip to unicast only when MCO set to desired version in all nodes
  pkg/config/node.go
Labels: approved, lgtm

#97 Add image build and push to the Makefile
  Makefile
Labels: approved, lgtm

#105 Bug 1888301: Add check for iptables rule to keepalived-monitor
  cmd/dynkeepalived/dynkeepalived.go
  cmd/monitor/monitor.go
  pkg/config/node.go
  pkg/monitor/dynkeepalived.go
  pkg/monitor/iptables.go
  pkg/monitor/monitor.go
  pkg/render/render.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
