Repository openshift/baremetal-runtimecfg, pull requests merged in 2020-07, with the labels that each got.

#71 BUG 1853889: Move haproxy port to 9445 due to conflict with KCM
  cmd/monitor/monitor.go
  cmd/runtimecfg/display.go
  cmd/runtimecfg/render.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#72 Bug 1857672: Also copy iptables scripts to /usr/sbin
  Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#65 Add support for unicast keepalived
  .gitignore
  Dockerfile
  cmd/unicastipserver/unicastipserver.go
  go.sum
  pkg/config/node.go
  pkg/monitor/dynkeepalived.go
  pkg/monitor/unicastipserver.go
Labels: approved, lgtm

#77 Stream dhclient stderr logs
  pkg/monitor/lease.go
Labels: approved, lgtm

#78 Change macvlan to be private mode
  pkg/monitor/lease.go
  pkg/monitor/lease_test.go
Labels: approved, lgtm

#75 Add support for Keepalived mode update
  pkg/config/node.go
  pkg/monitor/dynkeepalived.go
Labels: approved, lgtm

#70 Add check for iptables rule to keepalived-monitor
  cmd/dynkeepalived/dynkeepalived.go
  cmd/monitor/monitor.go
  pkg/config/node.go
  pkg/monitor/dynkeepalived.go
  pkg/monitor/iptables.go
  pkg/monitor/monitor.go
  pkg/render/render.go
Labels: approved, lgtm
