Repository openshift/baremetal-runtimecfg, pull requests merged in 2020-09, with the labels that each got.

#93 Bug 1872080: Add Dockerfile.openshift for CI
  Dockerfile.openshift
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#100 Change keepalived VIP subnet mask to host mask
  pkg/config/node.go
Labels: approved, lgtm

#92 Bug 1866265: Stop Keepalived on bootstrap after bootstrap completed
  pkg/config/node.go
  pkg/monitor/dynkeepalived.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#101 Bug 1872632: runtimecfg node-ip: allow running without VIPs
  cmd/runtimecfg/node-ip.go
  pkg/utils/utils.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
