Repository openshift/baremetal-runtimecfg, pull requests merged in 2021-06, with the labels that each got.

#135 Bug 1949859: Add Ironic healthcheck to bootstrap keepalived checks
  pkg/monitor/dynkeepalived.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#142 Remove Brad from OWNERS
  OWNERS
Labels: approved, lgtm

#141 Bug 1886572: Calculate keepalived priority for ingress
  pkg/config/node.go
  pkg/monitor/dynkeepalived.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#145 Bug 1974350: HAProxy-monitor: send reload only if cfg file changed
  pkg/monitor/monitor.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
