Repository openshift/baremetal-runtimecfg, pull requests merged in 2021-11, with the labels that each got.

#158 Bug 2022050: Add delay after sending bootstrap stop and start messages
  pkg/monitor/dynkeepalived.go
Labels: bugzilla/valid-bug, lgtm, approved, bugzilla/severity-urgent

#157 Bug 2021544: Ignore VIPs in node-ip show
  pkg/utils/addresses.go
Labels: bugzilla/valid-bug, lgtm, approved, bugzilla/severity-high

#159 Fix docker_test run
  Dockerfile.unittest
  docker-compose.yaml
Labels: lgtm, approved
