Repository openshift/baremetal-runtimecfg, pull requests merged in 2021-05, with the labels that each got.

#137 Bug 1957708: Keepalived- verify that unicast peers list isn't empty on master nodes
  pkg/monitor/dynkeepalived.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#138 Bug 1960716: Log the output of render operations
  pkg/render/render.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#133 Bug 1942506: 4.6 EUS node-ip handling extravaganza
  cmd/runtimecfg/node-ip.go
  pkg/config/net.go
  pkg/utils/addresses.go
  pkg/utils/addresses_test.go
  pkg/utils/utils.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
