Repository openshift/baremetal-runtimecfg, pull requests merged in 2022-10, with the labels that each got.

#197 Run go fmt
  pkg/config/node.go
Labels: lgtm, approved

#192 OCPBUGS-673: Apply ipv6 bind check to non-VIP case too
  cmd/runtimecfg/node-ip.go
Labels: bugzilla/valid-bug, lgtm, cherry-pick-approved, approved, backport-risk-assessed, jira/valid-bug

#199 OCPBUGS-2512: Improve IP address sort order for interface selection
  pkg/utils/addresses.go
  pkg/utils/addresses_test.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug
