Repository openshift/baremetal-runtimecfg, pull requests merged in 2023-04, with the labels that each got.

#231 OCPBUGS-11138: fix isUpgradeStillRunning()
  pkg/config/node.go
Labels: bugzilla/valid-bug, lgtm, cherry-pick-approved, approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#227 OCPBUGS-10695: Use subnet mask to detect IP stack
  pkg/utils/addresses.go
  pkg/utils/addresses_test.go
  pkg/utils/network.go
  pkg/utils/network_test.go
  pkg/utils/utils.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#233 OCPBUGS-11297: fix isUpgradeStillRunning()
  pkg/config/node.go
Labels: bugzilla/valid-bug, lgtm, cherry-pick-approved, approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#237 OCPBUGS-12729: Make nested dual stack VIP configs respect EnableUnicast
  pkg/monitor/dynkeepalived.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/valid-reference

#241 OCPBUGS-12739: In keepalived config print structs instead of pointers
  pkg/monitor/dynkeepalived.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#236 OCPBUGS-4370: Add label to VIP via keepalived
  test/data/keepalived.conf.tmpl
Labels: bugzilla/valid-bug, lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference
