Repository openshift/baremetal-runtimecfg, pull requests merged in 2023-06, with the labels that each got.

#254 OCPBUGS-12739: Use lazy match when getting IP from OVN
  pkg/config/node.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#256 OCPBUGS-12739: Use NonVirtualIP as a hint for selecting Peers
  pkg/config/node.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#258 OCPBUGS-12739: Fix bug with IP conversion using net.IP
  pkg/config/net.go
  pkg/config/node.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#260 OCPBUGS-14936: node: remove duplicate
  pkg/config/node.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#257 OCPBUGS-14403: Use machine-config state instead of comparing roles
  pkg/config/node.go
  pkg/monitor/dynkeepalived.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#251 Remove old scripts
  scripts/nodeip-finder
  scripts/non-virtual-ip
Labels: lgtm, approved

#262 [release-4.12] OCPBUGS-15315: Use machine-config state instead of comparing roles
  pkg/config/node.go
  pkg/monitor/dynkeepalived.go
Labels: lgtm, cherry-pick-approved, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
