Repository openshift/baremetal-runtimecfg, pull requests merged in 2024-08, with the labels that each got.

#326 OCPBUGS-38288: Distinguish NotExist from nil for keepalived sentinel file errors.
  pkg/monitor/dynkeepalived.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#328 OPNET-552: Move to stream9 for local builds
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#327 OCPBUGS-38281: Handle errors in iptables healthcheck
  pkg/monitor/iptables.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference
