Repository openshift/baremetal-runtimecfg, pull requests merged in 2024-05, with the labels that each got.

#310 Revert "OCPBUGS-32348: Make log level configurable"
  cmd/runtimecfg/node-ip.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#311 NO-ISSUE: Fix wrong golang version, bump to 1.21
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#308 OCPBUGS-29067: Fix generation of DNSUpstreams on cloud platforms
  pkg/config/node.go
  pkg/config/node_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
